[package]
name = "ingeoking"
version = "0.1.0"
edition = "2024"

[dependencies]
libevent-sys = "0.3.0"
libc = "0.2.172"

[features]
default = ["1-14-0"]
1-14-0 = []
dev = []
old = []

[lib]
crate-type = ["cdylib"]
